//Top 100 animes, used to pick random anime on home page fetch.
export const animes: Array<string> = [
  "Fullmetal Alchemist",
  "Death Note",
  "Cowboy Bebop",
  "Spirited Away",
  "Princess Mononoke",
  "(The) Melancholy of Haruhi Suzumiya",
  "Elfen Lied",
  "Neon Genesis Evangelion",
  "Code Geass: Lelouch of the Rebellion",
  "Bleach",
  "Code Geass: Lelouch of the Rebellion R2",
  "FLCL",
  "Naruto",
  "Samurai Champloo",
  "Trigun",
  "Gurren Lagann",
  "Rurouni Kenshin: Trust & Betrayal",
  "Howl's Moving Castle",
  "Full Metal Panic!",
  "Ouran High School Host Club",
  "Fullmetal Alchemist: Brotherhood",
  "Clannad",
  "Fruits Basket",
  "Akira",
  "Cowboy Bebop: The Movie",
  "Chobits",
  "Full Metal Panic? Fumoffu",
  "5 Centimeters Per Second",
  "Rurouni Kenshin",
  "(The) Girl Who Leapt Through Time",
  "Ghost in the Shell",
  "Clannad After Story",
  "Hellsing",
  "Final Fantasy VII: Advent Children",
  "Azumanga Daioh",
  "Fullmetal Alchemist: The Movie - Conqueror of Shamballa",
  "Ghost in the Shell: Stand Alone Complex",
  "Nausicaä of the Valley of the Wind",
  "Mushi-Shi",
  "Darker than Black",
  "Steins;Gate",
  "Fate/stay night",
  "Claymore",
  "Toradora!",
  "Inuyasha",
  "Castle in the Sky",
  "Full Metal Panic! The Second Raid",
  "Black Lagoon",
  "Blood+",
  "Angel Beats!",
  "Neon Genesis Evangelion: The End of Evangelion",
  "My Neighbor Totoro",
  "Grave of the Fireflies",
  "Dragon Ball Z",
  "Eureka Seven",
  "Air",
  "Love Hina",
  "Berserk",
  "Last Exile",
  "When They Cry - Higurashi",
  "GTO: Great Teacher Onizuka",
  "Baccano!",
  "Wolf's Rain",
  "Welcome to the NHK",
  "Sword Art Online",
  "Serial Experiments Lain",
  "Shakugan no Shana",
  "Haibane Renmei",
  "One Piece",
  "Attack on Titan",
  "Kiki's Delivery Service",
  "Naruto Shippūden",
  "(The) Vision of Escaflowne",
  "Samurai 7",
  "Soul Eater",
  "Ergo Proxy",
  "Black Lagoon: The Second Barrage",
  "Spice and Wolf",
  "School Rumble",
  "Lucky Star",
  "Eden of the East",
  "Kanon",
  "Gungrave",
  "Puella Magi Madoka Magica",
  "Dragon Ball",
  "Monster",
  "High School of the Dead",
  "Summer Wars",
  "Chrono Crusade",
  "Bakemonogatari",
  "anohana: The Flower We Saw That Day",
  "Gunslinger Girl",
  "Lunar Legend Tsukihime",
  "(The) Familiar of Zero",
  "R.O.D -The TV-",
];
