export type CountryType = {
  name: string
  code: string
  label: string
  value: string
}

export const countries = [
  {
    name: "Afghanistan",
    code: "AF",
    label: "Afghanistan - AF",
    value: "Afghanistan - AF",
  },
  {
    name: "Åland Islands",
    code: "AX",
    label: "Åland Islands - AX",
    value: "Åland Islands - AX",
  },
  {
    name: "Albania",
    code: "AL",
    label: "Albania - AL",
    value: "Albania - AL",
  },
  {
    name: "Algeria",
    code: "DZ",
    label: "Algeria - DZ",
    value: "Algeria - DZ",
  },
  {
    name: "American Samoa",
    code: "AS",
    label: "American Samoa - AS",
    value: "American Samoa - AS",
  },
  {
    name: "AndorrA",
    code: "AD",
    label: "AndorrA - AD",
    value: "AndorrA - AD",
  },
  {
    name: "Angola",
    code: "AO",
    label: "Angola - AO",
    value: "Angola - AO",
  },
  {
    name: "Anguilla",
    code: "AI",
    label: "Anguilla - AI",
    value: "Anguilla - AI",
  },
  {
    name: "Antarctica",
    code: "AQ",
    label: "Antarctica - AQ",
    value: "Antarctica - AQ",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    label: "Antigua and Barbuda - AG",
    value: "Antigua and Barbuda - AG",
  },
  {
    name: "Argentina",
    code: "AR",
    label: "Argentina - AR",
    value: "Argentina - AR",
  },
  {
    name: "Armenia",
    code: "AM",
    label: "Armenia - AM",
    value: "Armenia - AM",
  },
  {
    name: "Aruba",
    code: "AW",
    label: "Aruba - AW",
    value: "Aruba - AW",
  },
  {
    name: "Australia",
    code: "AU",
    label: "Australia - AU",
    value: "Australia - AU",
  },
  {
    name: "Austria",
    code: "AT",
    label: "Austria - AT",
    value: "Austria - AT",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    label: "Azerbaijan - AZ",
    value: "Azerbaijan - AZ",
  },
  {
    name: "Bahamas",
    code: "BS",
    label: "Bahamas - BS",
    value: "Bahamas - BS",
  },
  {
    name: "Bahrain",
    code: "BH",
    label: "Bahrain - BH",
    value: "Bahrain - BH",
  },
  {
    name: "Bangladesh",
    code: "BD",
    label: "Bangladesh - BD",
    value: "Bangladesh - BD",
  },
  {
    name: "Barbados",
    code: "BB",
    label: "Barbados - BB",
    value: "Barbados - BB",
  },
  {
    name: "Belarus",
    code: "BY",
    label: "Belarus - BY",
    value: "Belarus - BY",
  },
  {
    name: "Belgium",
    code: "BE",
    label: "Belgium - BE",
    value: "Belgium - BE",
  },
  {
    name: "Belize",
    code: "BZ",
    label: "Belize - BZ",
    value: "Belize - BZ",
  },
  {
    name: "Benin",
    code: "BJ",
    label: "Benin - BJ",
    value: "Benin - BJ",
  },
  {
    name: "Bermuda",
    code: "BM",
    label: "Bermuda - BM",
    value: "Bermuda - BM",
  },
  {
    name: "Bhutan",
    code: "BT",
    label: "Bhutan - BT",
    value: "Bhutan - BT",
  },
  {
    name: "Bolivia",
    code: "BO",
    label: "Bolivia - BO",
    value: "Bolivia - BO",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    label: "Bosnia and Herzegovina - BA",
    value: "Bosnia and Herzegovina - BA",
  },
  {
    name: "Botswana",
    code: "BW",
    label: "Botswana - BW",
    value: "Botswana - BW",
  },
  {
    name: "Bouvet Island",
    code: "BV",
    label: "Bouvet Island - BV",
    value: "Bouvet Island - BV",
  },
  {
    name: "Brazil",
    code: "BR",
    label: "Brazil - BR",
    value: "Brazil - BR",
  },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    label: "British Indian Ocean Territory - IO",
    value: "British Indian Ocean Territory - IO",
  },
  {
    name: "Brunei Darussalam",
    code: "BN",
    label: "Brunei Darussalam - BN",
    value: "Brunei Darussalam - BN",
  },
  {
    name: "Bulgaria",
    code: "BG",
    label: "Bulgaria - BG",
    value: "Bulgaria - BG",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    label: "Burkina Faso - BF",
    value: "Burkina Faso - BF",
  },
  {
    name: "Burundi",
    code: "BI",
    label: "Burundi - BI",
    value: "Burundi - BI",
  },
  {
    name: "Cambodia",
    code: "KH",
    label: "Cambodia - KH",
    value: "Cambodia - KH",
  },
  {
    name: "Cameroon",
    code: "CM",
    label: "Cameroon - CM",
    value: "Cameroon - CM",
  },
  {
    name: "Canada",
    code: "CA",
    label: "Canada - CA",
    value: "Canada - CA",
  },
  {
    name: "Cape Verde",
    code: "CV",
    label: "Cape Verde - CV",
    value: "Cape Verde - CV",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    label: "Cayman Islands - KY",
    value: "Cayman Islands - KY",
  },
  {
    name: "Central African Republic",
    code: "CF",
    label: "Central African Republic - CF",
    value: "Central African Republic - CF",
  },
  {
    name: "Chad",
    code: "TD",
    label: "Chad - TD",
    value: "Chad - TD",
  },
  {
    name: "Chile",
    code: "CL",
    label: "Chile - CL",
    value: "Chile - CL",
  },
  {
    name: "China",
    code: "CN",
    label: "China - CN",
    value: "China - CN",
  },
  {
    name: "Christmas Island",
    code: "CX",
    label: "Christmas Island - CX",
    value: "Christmas Island - CX",
  },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    label: "Cocos (Keeling) Islands - CC",
    value: "Cocos (Keeling) Islands - CC",
  },
  {
    name: "Colombia",
    code: "CO",
    label: "Colombia - CO",
    value: "Colombia - CO",
  },
  {
    name: "Comoros",
    code: "KM",
    label: "Comoros - KM",
    value: "Comoros - KM",
  },
  {
    name: "Congo",
    code: "CG",
    label: "Congo - CG",
    value: "Congo - CG",
  },
  {
    name: "Congo, The Democratic Republic of the",
    code: "CD",
    label: "Congo, The Democratic Republic of the - CD",
    value: "Congo, The Democratic Republic of the - CD",
  },
  {
    name: "Cook Islands",
    code: "CK",
    label: "Cook Islands - CK",
    value: "Cook Islands - CK",
  },
  {
    name: "Costa Rica",
    code: "CR",
    label: "Costa Rica - CR",
    value: "Costa Rica - CR",
  },
  {
    name: "Croatia",
    code: "HR",
    label: "Croatia - HR",
    value: "Croatia - HR",
  },
  {
    name: "Cuba",
    code: "CU",
    label: "Cuba - CU",
    value: "Cuba - CU",
  },
  {
    name: "Cyprus",
    code: "CY",
    label: "Cyprus - CY",
    value: "Cyprus - CY",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    label: "Czech Republic - CZ",
    value: "Czech Republic - CZ",
  },
  {
    name: "Denmark",
    code: "DK",
    label: "Denmark - DK",
    value: "Denmark - DK",
  },
  {
    name: "Djibouti",
    code: "DJ",
    label: "Djibouti - DJ",
    value: "Djibouti - DJ",
  },
  {
    name: "Dominica",
    code: "DM",
    label: "Dominica - DM",
    value: "Dominica - DM",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    label: "Dominican Republic - DO",
    value: "Dominican Republic - DO",
  },
  {
    name: "Ecuador",
    code: "EC",
    label: "Ecuador - EC",
    value: "Ecuador - EC",
  },
  {
    name: "Egypt",
    code: "EG",
    label: "Egypt - EG",
    value: "Egypt - EG",
  },
  {
    name: "El Salvador",
    code: "SV",
    label: "El Salvador - SV",
    value: "El Salvador - SV",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    label: "Equatorial Guinea - GQ",
    value: "Equatorial Guinea - GQ",
  },
  {
    name: "Eritrea",
    code: "ER",
    label: "Eritrea - ER",
    value: "Eritrea - ER",
  },
  {
    name: "Estonia",
    code: "EE",
    label: "Estonia - EE",
    value: "Estonia - EE",
  },
  {
    name: "Ethiopia",
    code: "ET",
    label: "Ethiopia - ET",
    value: "Ethiopia - ET",
  },
  {
    name: "Falkland Islands (Malvinas)",
    code: "FK",
    label: "Falkland Islands (Malvinas) - FK",
    value: "Falkland Islands (Malvinas) - FK",
  },
  {
    name: "Faroe Islands",
    code: "FO",
    label: "Faroe Islands - FO",
    value: "Faroe Islands - FO",
  },
  {
    name: "Fiji",
    code: "FJ",
    label: "Fiji - FJ",
    value: "Fiji - FJ",
  },
  {
    name: "Finland",
    code: "FI",
    label: "Finland - FI",
    value: "Finland - FI",
  },
  {
    name: "France",
    code: "FR",
    label: "France - FR",
    value: "France - FR",
  },
  {
    name: "French Guiana",
    code: "GF",
    label: "French Guiana - GF",
    value: "French Guiana - GF",
  },
  {
    name: "French Polynesia",
    code: "PF",
    label: "French Polynesia - PF",
    value: "French Polynesia - PF",
  },
  {
    name: "French Southern Territories",
    code: "TF",
    label: "French Southern Territories - TF",
    value: "French Southern Territories - TF",
  },
  {
    name: "Gabon",
    code: "GA",
    label: "Gabon - GA",
    value: "Gabon - GA",
  },
  {
    name: "Gambia",
    code: "GM",
    label: "Gambia - GM",
    value: "Gambia - GM",
  },
  {
    name: "Georgia",
    code: "GE",
    label: "Georgia - GE",
    value: "Georgia - GE",
  },
  {
    name: "Germany",
    code: "DE",
    label: "Germany - DE",
    value: "Germany - DE",
  },
  {
    name: "Ghana",
    code: "GH",
    label: "Ghana - GH",
    value: "Ghana - GH",
  },
  {
    name: "Gibraltar",
    code: "GI",
    label: "Gibraltar - GI",
    value: "Gibraltar - GI",
  },
  {
    name: "Greece",
    code: "GR",
    label: "Greece - GR",
    value: "Greece - GR",
  },
  {
    name: "Greenland",
    code: "GL",
    label: "Greenland - GL",
    value: "Greenland - GL",
  },
  {
    name: "Grenada",
    code: "GD",
    label: "Grenada - GD",
    value: "Grenada - GD",
  },
  {
    name: "Guadeloupe",
    code: "GP",
    label: "Guadeloupe - GP",
    value: "Guadeloupe - GP",
  },
  {
    name: "Guam",
    code: "GU",
    label: "Guam - GU",
    value: "Guam - GU",
  },
  {
    name: "Guatemala",
    code: "GT",
    label: "Guatemala - GT",
    value: "Guatemala - GT",
  },
  {
    name: "Guernsey",
    code: "GG",
    label: "Guernsey - GG",
    value: "Guernsey - GG",
  },
  {
    name: "Guinea",
    code: "GN",
    label: "Guinea - GN",
    value: "Guinea - GN",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    label: "Guinea-Bissau - GW",
    value: "Guinea-Bissau - GW",
  },
  {
    name: "Guyana",
    code: "GY",
    label: "Guyana - GY",
    value: "Guyana - GY",
  },
  {
    name: "Haiti",
    code: "HT",
    label: "Haiti - HT",
    value: "Haiti - HT",
  },
  {
    name: "Heard Island and Mcdonald Islands",
    code: "HM",
    label: "Heard Island and Mcdonald Islands - HM",
    value: "Heard Island and Mcdonald Islands - HM",
  },
  {
    name: "Holy See (Vatican City State)",
    code: "VA",
    label: "Holy See (Vatican City State) - VA",
    value: "Holy See (Vatican City State) - VA",
  },
  {
    name: "Honduras",
    code: "HN",
    label: "Honduras - HN",
    value: "Honduras - HN",
  },
  {
    name: "Hong Kong",
    code: "HK",
    label: "Hong Kong - HK",
    value: "Hong Kong - HK",
  },
  {
    name: "Hungary",
    code: "HU",
    label: "Hungary - HU",
    value: "Hungary - HU",
  },
  {
    name: "Iceland",
    code: "IS",
    label: "Iceland - IS",
    value: "Iceland - IS",
  },
  {
    name: "India",
    code: "IN",
    label: "India - IN",
    value: "India - IN",
  },
  {
    name: "Indonesia",
    code: "ID",
    label: "Indonesia - ID",
    value: "Indonesia - ID",
  },
  {
    name: "Iran, Islamic Republic Of",
    code: "IR",
    label: "Iran, Islamic Republic Of - IR",
    value: "Iran, Islamic Republic Of - IR",
  },
  {
    name: "Iraq",
    code: "IQ",
    label: "Iraq - IQ",
    value: "Iraq - IQ",
  },
  {
    name: "Ireland",
    code: "IE",
    label: "Ireland - IE",
    value: "Ireland - IE",
  },
  {
    name: "Isle of Man",
    code: "IM",
    label: "Isle of Man - IM",
    value: "Isle of Man - IM",
  },
  {
    name: "Israel",
    code: "IL",
    label: "Israel - IL",
    value: "Israel - IL",
  },
  {
    name: "Italy",
    code: "IT",
    label: "Italy - IT",
    value: "Italy - IT",
  },
  {
    name: "Jamaica",
    code: "JM",
    label: "Jamaica - JM",
    value: "Jamaica - JM",
  },
  {
    name: "Japan",
    code: "JP",
    label: "Japan - JP",
    value: "Japan - JP",
  },
  {
    name: "Jersey",
    code: "JE",
    label: "Jersey - JE",
    value: "Jersey - JE",
  },
  {
    name: "Jordan",
    code: "JO",
    label: "Jordan - JO",
    value: "Jordan - JO",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    label: "Kazakhstan - KZ",
    value: "Kazakhstan - KZ",
  },
  {
    name: "Kenya",
    code: "KE",
    label: "Kenya - KE",
    value: "Kenya - KE",
  },
  {
    name: "Kiribati",
    code: "KI",
    label: "Kiribati - KI",
    value: "Kiribati - KI",
  },
  {
    name: "Korea, Republic of",
    code: "KR",
    label: "Korea, Republic of - KR",
    value: "Korea, Republic of - KR",
  },
  {
    name: "Kuwait",
    code: "KW",
    label: "Kuwait - KW",
    value: "Kuwait - KW",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    label: "Kyrgyzstan - KG",
    value: "Kyrgyzstan - KG",
  },
  {
    name: "Latvia",
    code: "LV",
    label: "Latvia - LV",
    value: "Latvia - LV",
  },
  {
    name: "Lebanon",
    code: "LB",
    label: "Lebanon - LB",
    value: "Lebanon - LB",
  },
  {
    name: "Lesotho",
    code: "LS",
    label: "Lesotho - LS",
    value: "Lesotho - LS",
  },
  {
    name: "Liberia",
    code: "LR",
    label: "Liberia - LR",
    value: "Liberia - LR",
  },
  {
    name: "Libyan Arab Jamahiriya",
    code: "LY",
    label: "Libyan Arab Jamahiriya - LY",
    value: "Libyan Arab Jamahiriya - LY",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    label: "Liechtenstein - LI",
    value: "Liechtenstein - LI",
  },
  {
    name: "Lithuania",
    code: "LT",
    label: "Lithuania - LT",
    value: "Lithuania - LT",
  },
  {
    name: "Luxembourg",
    code: "LU",
    label: "Luxembourg - LU",
    value: "Luxembourg - LU",
  },
  {
    name: "Macao",
    code: "MO",
    label: "Macao - MO",
    value: "Macao - MO",
  },
  {
    name: "Macedonia, The Former Yugoslav Republic of",
    code: "MK",
    label: "Macedonia, The Former Yugoslav Republic of - MK",
    value: "Macedonia, The Former Yugoslav Republic of - MK",
  },
  {
    name: "Madagascar",
    code: "MG",
    label: "Madagascar - MG",
    value: "Madagascar - MG",
  },
  {
    name: "Malawi",
    code: "MW",
    label: "Malawi - MW",
    value: "Malawi - MW",
  },
  {
    name: "Malaysia",
    code: "MY",
    label: "Malaysia - MY",
    value: "Malaysia - MY",
  },
  {
    name: "Maldives",
    code: "MV",
    label: "Maldives - MV",
    value: "Maldives - MV",
  },
  {
    name: "Mali",
    code: "ML",
    label: "Mali - ML",
    value: "Mali - ML",
  },
  {
    name: "Malta",
    code: "MT",
    label: "Malta - MT",
    value: "Malta - MT",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    label: "Marshall Islands - MH",
    value: "Marshall Islands - MH",
  },
  {
    name: "Martinique",
    code: "MQ",
    label: "Martinique - MQ",
    value: "Martinique - MQ",
  },
  {
    name: "Mauritania",
    code: "MR",
    label: "Mauritania - MR",
    value: "Mauritania - MR",
  },
  {
    name: "Mauritius",
    code: "MU",
    label: "Mauritius - MU",
    value: "Mauritius - MU",
  },
  {
    name: "Mayotte",
    code: "YT",
    label: "Mayotte - YT",
    value: "Mayotte - YT",
  },
  {
    name: "Mexico",
    code: "MX",
    label: "Mexico - MX",
    value: "Mexico - MX",
  },
  {
    name: "Micronesia, Federated States of",
    code: "FM",
    label: "Micronesia, Federated States of - FM",
    value: "Micronesia, Federated States of - FM",
  },
  {
    name: "Moldova, Republic of",
    code: "MD",
    label: "Moldova, Republic of - MD",
    value: "Moldova, Republic of - MD",
  },
  {
    name: "Monaco",
    code: "MC",
    label: "Monaco - MC",
    value: "Monaco - MC",
  },
  {
    name: "Mongolia",
    code: "MN",
    label: "Mongolia - MN",
    value: "Mongolia - MN",
  },
  {
    name: "Montserrat",
    code: "MS",
    label: "Montserrat - MS",
    value: "Montserrat - MS",
  },
  {
    name: "Morocco",
    code: "MA",
    label: "Morocco - MA",
    value: "Morocco - MA",
  },
  {
    name: "Mozambique",
    code: "MZ",
    label: "Mozambique - MZ",
    value: "Mozambique - MZ",
  },
  {
    name: "Myanmar",
    code: "MM",
    label: "Myanmar - MM",
    value: "Myanmar - MM",
  },
  {
    name: "Namibia",
    code: "NA",
    label: "Namibia - NA",
    value: "Namibia - NA",
  },
  {
    name: "Nauru",
    code: "NR",
    label: "Nauru - NR",
    value: "Nauru - NR",
  },
  {
    name: "Nepal",
    code: "NP",
    label: "Nepal - NP",
    value: "Nepal - NP",
  },
  {
    name: "Netherlands",
    code: "NL",
    label: "Netherlands - NL",
    value: "Netherlands - NL",
  },
  {
    name: "Netherlands Antilles",
    code: "AN",
    label: "Netherlands Antilles - AN",
    value: "Netherlands Antilles - AN",
  },
  {
    name: "New Caledonia",
    code: "NC",
    label: "New Caledonia - NC",
    value: "New Caledonia - NC",
  },
  {
    name: "New Zealand",
    code: "NZ",
    label: "New Zealand - NZ",
    value: "New Zealand - NZ",
  },
  {
    name: "Nicaragua",
    code: "NI",
    label: "Nicaragua - NI",
    value: "Nicaragua - NI",
  },
  {
    name: "Niger",
    code: "NE",
    label: "Niger - NE",
    value: "Niger - NE",
  },
  {
    name: "Nigeria",
    code: "NG",
    label: "Nigeria - NG",
    value: "Nigeria - NG",
  },
  {
    name: "Niue",
    code: "NU",
    label: "Niue - NU",
    value: "Niue - NU",
  },
  {
    name: "Norfolk Island",
    code: "NF",
    label: "Norfolk Island - NF",
    value: "Norfolk Island - NF",
  },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    label: "Northern Mariana Islands - MP",
    value: "Northern Mariana Islands - MP",
  },
  {
    name: "Norway",
    code: "NO",
    label: "Norway - NO",
    value: "Norway - NO",
  },
  {
    name: "Oman",
    code: "OM",
    label: "Oman - OM",
    value: "Oman - OM",
  },
  {
    name: "Pakistan",
    code: "PK",
    label: "Pakistan - PK",
    value: "Pakistan - PK",
  },
  {
    name: "Palau",
    code: "PW",
    label: "Palau - PW",
    value: "Palau - PW",
  },
  {
    name: "Palestinian Territory, Occupied",
    code: "PS",
    label: "Palestinian Territory, Occupied - PS",
    value: "Palestinian Territory, Occupied - PS",
  },
  {
    name: "Panama",
    code: "PA",
    label: "Panama - PA",
    value: "Panama - PA",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    label: "Papua New Guinea - PG",
    value: "Papua New Guinea - PG",
  },
  {
    name: "Paraguay",
    code: "PY",
    label: "Paraguay - PY",
    value: "Paraguay - PY",
  },
  {
    name: "Peru",
    code: "PE",
    label: "Peru - PE",
    value: "Peru - PE",
  },
  {
    name: "Philippines",
    code: "PH",
    label: "Philippines - PH",
    value: "Philippines - PH",
  },
  {
    name: "Pitcairn",
    code: "PN",
    label: "Pitcairn - PN",
    value: "Pitcairn - PN",
  },
  {
    name: "Poland",
    code: "PL",
    label: "Poland - PL",
    value: "Poland - PL",
  },
  {
    name: "Portugal",
    code: "PT",
    label: "Portugal - PT",
    value: "Portugal - PT",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    label: "Puerto Rico - PR",
    value: "Puerto Rico - PR",
  },
  {
    name: "Qatar",
    code: "QA",
    label: "Qatar - QA",
    value: "Qatar - QA",
  },
  {
    name: "Reunion",
    code: "RE",
    label: "Reunion - RE",
    value: "Reunion - RE",
  },
  {
    name: "Romania",
    code: "RO",
    label: "Romania - RO",
    value: "Romania - RO",
  },
  {
    name: "Russian Federation",
    code: "RU",
    label: "Russian Federation - RU",
    value: "Russian Federation - RU",
  },
  {
    name: "RWANDA",
    code: "RW",
    label: "RWANDA - RW",
    value: "RWANDA - RW",
  },
  {
    name: "Saint Helena",
    code: "SH",
    label: "Saint Helena - SH",
    value: "Saint Helena - SH",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    label: "Saint Kitts and Nevis - KN",
    value: "Saint Kitts and Nevis - KN",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    label: "Saint Lucia - LC",
    value: "Saint Lucia - LC",
  },
  {
    name: "Saint Pierre and Miquelon",
    code: "PM",
    label: "Saint Pierre and Miquelon - PM",
    value: "Saint Pierre and Miquelon - PM",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    label: "Saint Vincent and the Grenadines - VC",
    value: "Saint Vincent and the Grenadines - VC",
  },
  {
    name: "Samoa",
    code: "WS",
    label: "Samoa - WS",
    value: "Samoa - WS",
  },
  {
    name: "San Marino",
    code: "SM",
    label: "San Marino - SM",
    value: "San Marino - SM",
  },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    label: "Sao Tome and Principe - ST",
    value: "Sao Tome and Principe - ST",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    label: "Saudi Arabia - SA",
    value: "Saudi Arabia - SA",
  },
  {
    name: "Senegal",
    code: "SN",
    label: "Senegal - SN",
    value: "Senegal - SN",
  },
  {
    name: "Serbia and Montenegro",
    code: "CS",
    label: "Serbia and Montenegro - CS",
    value: "Serbia and Montenegro - CS",
  },
  {
    name: "Seychelles",
    code: "SC",
    label: "Seychelles - SC",
    value: "Seychelles - SC",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    label: "Sierra Leone - SL",
    value: "Sierra Leone - SL",
  },
  {
    name: "Singapore",
    code: "SG",
    label: "Singapore - SG",
    value: "Singapore - SG",
  },
  {
    name: "Slovakia",
    code: "SK",
    label: "Slovakia - SK",
    value: "Slovakia - SK",
  },
  {
    name: "Slovenia",
    code: "SI",
    label: "Slovenia - SI",
    value: "Slovenia - SI",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    label: "Solomon Islands - SB",
    value: "Solomon Islands - SB",
  },
  {
    name: "Somalia",
    code: "SO",
    label: "Somalia - SO",
    value: "Somalia - SO",
  },
  {
    name: "South Africa",
    code: "ZA",
    label: "South Africa - ZA",
    value: "South Africa - ZA",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    label: "South Georgia and the South Sandwich Islands - GS",
    value: "South Georgia and the South Sandwich Islands - GS",
  },
  {
    name: "Spain",
    code: "ES",
    label: "Spain - ES",
    value: "Spain - ES",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    label: "Sri Lanka - LK",
    value: "Sri Lanka - LK",
  },
  {
    name: "Sudan",
    code: "SD",
    label: "Sudan - SD",
    value: "Sudan - SD",
  },
  {
    name: "Suriname",
    code: "SR",
    label: "Suriname - SR",
    value: "Suriname - SR",
  },
  {
    name: "Svalbard and Jan Mayen",
    code: "SJ",
    label: "Svalbard and Jan Mayen - SJ",
    value: "Svalbard and Jan Mayen - SJ",
  },
  {
    name: "Swaziland",
    code: "SZ",
    label: "Swaziland - SZ",
    value: "Swaziland - SZ",
  },
  {
    name: "Sweden",
    code: "SE",
    label: "Sweden - SE",
    value: "Sweden - SE",
  },
  {
    name: "Switzerland",
    code: "CH",
    label: "Switzerland - CH",
    value: "Switzerland - CH",
  },
  {
    name: "Syrian Arab Republic",
    code: "SY",
    label: "Syrian Arab Republic - SY",
    value: "Syrian Arab Republic - SY",
  },
  {
    name: "Taiwan, Province of China",
    code: "TW",
    label: "Taiwan, Province of China - TW",
    value: "Taiwan, Province of China - TW",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    label: "Tajikistan - TJ",
    value: "Tajikistan - TJ",
  },
  {
    name: "Tanzania, United Republic of",
    code: "TZ",
    label: "Tanzania, United Republic of - TZ",
    value: "Tanzania, United Republic of - TZ",
  },
  {
    name: "Thailand",
    code: "TH",
    label: "Thailand - TH",
    value: "Thailand - TH",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    label: "Timor-Leste - TL",
    value: "Timor-Leste - TL",
  },
  {
    name: "Togo",
    code: "TG",
    label: "Togo - TG",
    value: "Togo - TG",
  },
  {
    name: "Tokelau",
    code: "TK",
    label: "Tokelau - TK",
    value: "Tokelau - TK",
  },
  {
    name: "Tonga",
    code: "TO",
    label: "Tonga - TO",
    value: "Tonga - TO",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    label: "Trinidad and Tobago - TT",
    value: "Trinidad and Tobago - TT",
  },
  {
    name: "Tunisia",
    code: "TN",
    label: "Tunisia - TN",
    value: "Tunisia - TN",
  },
  {
    name: "Turkey",
    code: "TR",
    label: "Turkey - TR",
    value: "Turkey - TR",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    label: "Turkmenistan - TM",
    value: "Turkmenistan - TM",
  },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    label: "Turks and Caicos Islands - TC",
    value: "Turks and Caicos Islands - TC",
  },
  {
    name: "Tuvalu",
    code: "TV",
    label: "Tuvalu - TV",
    value: "Tuvalu - TV",
  },
  {
    name: "Uganda",
    code: "UG",
    label: "Uganda - UG",
    value: "Uganda - UG",
  },
  {
    name: "Ukraine",
    code: "UA",
    label: "Ukraine - UA",
    value: "Ukraine - UA",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    label: "United Arab Emirates - AE",
    value: "United Arab Emirates - AE",
  },
  {
    name: "United Kingdom",
    code: "GB",
    label: "United Kingdom - GB",
    value: "United Kingdom - GB",
  },
  {
    name: "United States",
    code: "US",
    label: "United States - US",
    value: "United States - US",
  },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    label: "United States Minor Outlying Islands - UM",
    value: "United States Minor Outlying Islands - UM",
  },
  {
    name: "Uruguay",
    code: "UY",
    label: "Uruguay - UY",
    value: "Uruguay - UY",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    label: "Uzbekistan - UZ",
    value: "Uzbekistan - UZ",
  },
  {
    name: "Vanuatu",
    code: "VU",
    label: "Vanuatu - VU",
    value: "Vanuatu - VU",
  },
  {
    name: "Venezuela",
    code: "VE",
    label: "Venezuela - VE",
    value: "Venezuela - VE",
  },
  {
    name: "Viet Nam",
    code: "VN",
    label: "Viet Nam - VN",
    value: "Viet Nam - VN",
  },
  {
    name: "Virgin Islands, British",
    code: "VG",
    label: "Virgin Islands, British - VG",
    value: "Virgin Islands, British - VG",
  },
  {
    name: "Virgin Islands, U.S.",
    code: "VI",
    label: "Virgin Islands, U.S. - VI",
    value: "Virgin Islands, U.S. - VI",
  },
  {
    name: "Wallis and Futuna",
    code: "WF",
    label: "Wallis and Futuna - WF",
    value: "Wallis and Futuna - WF",
  },
  {
    name: "Western Sahara",
    code: "EH",
    label: "Western Sahara - EH",
    value: "Western Sahara - EH",
  },
  {
    name: "Yemen",
    code: "YE",
    label: "Yemen - YE",
    value: "Yemen - YE",
  },
  {
    name: "Zambia",
    code: "ZM",
    label: "Zambia - ZM",
    value: "Zambia - ZM",
  },
  {
    name: "Zimbabw",
    code: "ZN",
    label: "Zimbabw - ZN",
    value: "Zimbabw - ZN",
  },
]
